export const AppImages = {
  backIcon: require("../../Assets/Images/Back.png"),
  backWhite: require("../../Assets/Images/backWhite.png"),
  greenBookIcon: require("../../Assets/Images/BookGreen.png"),
  greyBookIcon: require("../../Assets/Images/BookGrey.png"),
  greenCameraIcon: require("../../Assets/Images/Camera.png"),
  greenChatIcon: require("../../Assets/Images/ChatGreen.png"),
  curveBigHeaderImage: require("../../Assets/Images/CurveHeaderBig.png"),
  curveSmallHeaderImage: require("../../Assets/Images/CurveHeaderSmall.png"),
  darkGreenEditIcon: require("../../Assets/Images/EditGreenDark.png"),
  lightGreenEditIcon: require("../../Assets/Images/EditGreenLight.png"),
  gradientButtonImage: require("../../Assets/Images/GradientButton.png"),
  GradientButtonTransparent: require("../../Assets/Images/GradientButtonTransparent.png"),
  greenHeartIcon: require("../../Assets/Images/HeartGreen.png"),
  greyOutlineHeartIcon: require("../../Assets/Images/HeartGreyOutline.png"),
  greenOutlineHeartIcon: require("../../Assets/Images/heartGreenOutline.png"),
  redHeartIcon: require("../../Assets/Images/HeartRed.png"),
  greenLockIcon: require("../../Assets/Images/LockGreen.png"),
  greenLockSimpleIcon: require("../../Assets/Images/LockGreenSimple.png"),
  redLogOutIcon: require("../../Assets/Images/Logout.png"),
  greenMailIcon: require("../../Assets/Images/MailGreen.png"),
  myTrackerIcon: require("../../Assets/Images/MyTrackerIcon.png"),
  greenNoteIcon: require("../../Assets/Images/NoteGreen.png"),
  greenPillIcon: require("../../Assets/Images/RectangleRound.png"),
  greyStethoscopeIcon: require("../../Assets/Images/Seth.png"),
  greenStethoscopeIcon: require("../../Assets/Images/sethGreen.png"),
  greenUserIcon: require("../../Assets/Images/UserGreen.png"),
  greyUserIcon: require("../../Assets/Images/UserGrey.png"),
  logoIcon: require("../../Assets/Images/logo.png"),
  contactUsIcon: require("../../Assets/Images/message.png"),
  searchIcon: require("../../Assets/Images/search.png"),
  stressReliefIcon: require("../../Assets/Images/StressRelief.png"),
  thankfulIcon: require("../../Assets/Images/Thankful.png"),
  skinPositivityIcon: require("../../Assets/Images/SkinPositivity.png"),
  selfLoveIcon: require("../../Assets/Images/SelfLove.png"),
  myAffirmationsIcon: require("../../Assets/Images/MyAffirmations.png"),
  depressionIcon: require("../../Assets/Images/Depression.png"),
  anxietyIcon: require("../../Assets/Images/Anxiety.png"),
  googleIcon: require("../../Assets/Images/google.png"),
  fbIcon: require("../../Assets/Images/fb.png"),
  appleIcon: require("../../Assets/Images/apple.png"),
  addMyAffirmation: require("../../Assets/Images/AddMyAffirmation.png"),
  deleteBlackIcon: require("../../Assets/Images/deleteBlack.png"),
  editBlackIcon: require("../../Assets/Images/editBlack.png"),
  shareBlackIcon: require("../../Assets/Images/shareBlack.png"),
  pauseGreenIcon: require("../../Assets/Images/pauseGreen.png"),
  pauseWhiteIcon: require("../../Assets/Images/pauseWhite.png"),
  playGreenIcon: require("../../Assets/Images/playGreen.png"),
  playWhiteIcon: require("../../Assets/Images/playWhite.png"),
  editWhiteIcon: require("../../Assets/Images/editWhite.png"),
  curveLightGreenHeaderImage: require("../../Assets/Images/curveLightGreenHeader.png"),
  addMyAffirmation: require("../../Assets/Images/AddMyAffirmation.png"),
  dropdownicon: require("../../Assets/Images/dropdownicon.png"),
  mike: require("../../Assets/Images/mike.png"),
  bigRectangleRound: require("../../Assets/Images/bigRectangleRound.png"),
  upArrow: require("../../Assets/Images/upArrow.png"),
  leftArrow: require("../../Assets/Images/leftArrow.png"),
  rightArrow: require("../../Assets/Images/rightArrow.png"),
  editEntry: require("../../Assets/Images/editEntry.png"),
  edit: require("../../Assets/Images/edit.png"),
  toggle: require("../../Assets/Images/toggle.png"),
  calender: require("../../Assets/Images/calender.png"),
  calenderWhite: require("../../Assets/Images/calenderWhite.png"),
  calenderDark: require("../../Assets/Images/calenderDark.png"),
  simpleDownArrow: require("../../Assets/Images/simpleDownArrow.png"),
  simpleDownArrowDark: require("../../Assets/Images/simpleDownArrowDark.png"),
  simpleUpArrowDark: require("../../Assets/Images/simpleUpArrowDark.png"),
  simpleLeftArrowdark: require("../../Assets/Images/simpleLeftArrowdark.png"),
  simpleRightArrowdark: require("../../Assets/Images/simpleRightArrowdark.png"),
  simpleRightArrow: require("../../Assets/Images/simpleRightArrow.png"),
  goodSmile: require("../../Assets/Images/good.png"),
  badSmile: require("../../Assets/Images/bad.png"),
  okSmile: require("../../Assets/Images/ok.png"),
  dummyImage: require("../../Assets/Images/dummyImage.png"),
  dots: require("../../Assets/Images/dots.png"),
  bottomTab: require("../../Assets/Images/bottomTab.png"),
  ThreedotsWhite: require("../../Assets/Images/3dotsWhite.png"),
  sendButton: require("../../Assets/Images/sendButton.png"),
  downArrow: require("../../Assets/Images/downArrow.png"),
  userDummy: require("../../Assets/Images/userDummy.png"),
};

export const AppImagesExpo = [
  require("../../Assets/Images/Back.png"),
  require("../../Assets/Images/backWhite.png"),
  require("../../Assets/Images/BookGreen.png"),
  require("../../Assets/Images/BookGrey.png"),
  require("../../Assets/Images/Camera.png"),
  require("../../Assets/Images/ChatGreen.png"),
  require("../../Assets/Images/CurveHeaderBig.png"),
  require("../../Assets/Images/CurveHeaderSmall.png"),
  require("../../Assets/Images/EditGreenDark.png"),
  require("../../Assets/Images/EditGreenLight.png"),
  require("../../Assets/Images/GradientButton.png"),
  require("../../Assets/Images/GradientButtonTransparent.png"),
  require("../../Assets/Images/HeartGreen.png"),
  require("../../Assets/Images/HeartGreyOutline.png"),
  require("../../Assets/Images/heartGreenOutline.png"),
  require("../../Assets/Images/HeartRed.png"),
  require("../../Assets/Images/LockGreen.png"),
  require("../../Assets/Images/LockGreenSimple.png"),
  require("../../Assets/Images/Logout.png"),
  require("../../Assets/Images/MailGreen.png"),
  require("../../Assets/Images/MyTrackerIcon.png"),
  require("../../Assets/Images/NoteGreen.png"),
  require("../../Assets/Images/RectangleRound.png"),
  require("../../Assets/Images/Seth.png"),
  require("../../Assets/Images/sethGreen.png"),
  require("../../Assets/Images/UserGreen.png"),
  require("../../Assets/Images/UserGrey.png"),
  require("../../Assets/Images/logo.png"),
  require("../../Assets/Images/message.png"),
  require("../../Assets/Images/search.png"),
  require("../../Assets/Images/StressRelief.png"),
  require("../../Assets/Images/Thankful.png"),
  require("../../Assets/Images/SkinPositivity.png"),
  require("../../Assets/Images/SelfLove.png"),
  require("../../Assets/Images/MyAffirmations.png"),
  require("../../Assets/Images/Depression.png"),
  require("../../Assets/Images/Anxiety.png"),
  require("../../Assets/Images/google.png"),
  require("../../Assets/Images/fb.png"),
  require("../../Assets/Images/apple.png"),
  require("../../Assets/Images/AddMyAffirmation.png"),
  require("../../Assets/Images/deleteBlack.png"),
  require("../../Assets/Images/editBlack.png"),
  require("../../Assets/Images/shareBlack.png"),
  require("../../Assets/Images/pauseGreen.png"),
  require("../../Assets/Images/pauseWhite.png"),
  require("../../Assets/Images/playGreen.png"),
  require("../../Assets/Images/playWhite.png"),
  require("../../Assets/Images/editWhite.png"),
  require("../../Assets/Images/curveLightGreenHeader.png"),
  require("../../Assets/Images/AddMyAffirmation.png"),
  require("../../Assets/Images/dropdownicon.png"),
  require("../../Assets/Images/mike.png"),
  require("../../Assets/Images/bigRectangleRound.png"),
  require("../../Assets/Images/upArrow.png"),
  require("../../Assets/Images/leftArrow.png"),
  require("../../Assets/Images/rightArrow.png"),
  require("../../Assets/Images/editEntry.png"),
  require("../../Assets/Images/edit.png"),
  require("../../Assets/Images/toggle.png"),
  require("../../Assets/Images/calender.png"),
  require("../../Assets/Images/calenderWhite.png"),
  require("../../Assets/Images/calenderDark.png"),
  require("../../Assets/Images/simpleDownArrow.png"),
  require("../../Assets/Images/simpleDownArrowDark.png"),
  require("../../Assets/Images/simpleUpArrowDark.png"),
  require("../../Assets/Images/simpleLeftArrowdark.png"),
  require("../../Assets/Images/simpleRightArrowdark.png"),
  require("../../Assets/Images/simpleRightArrow.png"),
  require("../../Assets/Images/good.png"),
  require("../../Assets/Images/bad.png"),
  require("../../Assets/Images/ok.png"),
  require("../../Assets/Images/dummyImage.png"),
  require("../../Assets/Images/dots.png"),
  require("../../Assets/Images/bottomTab.png"),
  require("../../Assets/Images/3dotsWhite.png"),
  require("../../Assets/Images/sendButton.png"),
  require("../../Assets/Images/downArrow.png"),
  require("../../Assets/Images/userDummy.png"),
];
