export default AppConstants = {
    priorities: [
        "I already know my skin condition and want to learn more about how to live in my own skin",
        "I want a skin condition diagnosis and want to use the loveMySkin skin diagnosis tool",
        "I have no current skin condition and want to explore everything LoveMySkin has to offer"
    ],
    loremIpsum: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem.",
    welcomeBack: "Welcome Back",
    welcome: "Welcome",
    signIn: "Sign In",
    signUp: "sign Up",
    enterYourEmailAddress: "Enter your email address",
    enterYourPassword: "Enter your password",
    confirmYourPassword: "Confirm your password",
    forgotPassword: "Forgot Password",
    dontHaveAnAccount: "Dont Have an Account? Sign Up",
    haveAnAccount: "Have an Account? Sign In",
    submit: "Submit",
    whatisthebiggestPriority: "What is the biggest priority when it comes to your skin?",
    iDontWantToAnswerThis: "I don't want to answer this.",
    continue: "Continue",
    editProfile: "Edit Profile",
    contactUs: "Contact Us",
    privacyPolicy: "Privacy Policy",
    termsAndConditions: "Terms and Conditions",
    logout: "Logout",
    changePassword: "Change Password",
    saveChanges: "Save Changes",
    enterOldPassword: "Enter old password",
    enterNewPassword: "Enter new password",
    confirmNewPassword: "Confirm new password",
    firstName:"First name",
    lastName:"Last name",
    userId:"User Id",
    
}