// Login
export const API_LOGIN_LOAD = "API_LOGIN_LOAD";
export const API_LOGIN_START = "API_LOGIN_START";
export const API_LOGIN_SUCCESS = "API_LOGIN_SUCCESS";
export const API_LOGIN_ERROR = "API_LOGIN_ERROR";

// Signup
export const API_SIGNUP_LOAD = "API_SIGNUP_LOAD";
export const API_SIGNUP_START = "API_SIGNUP_START";
export const API_SIGNUP_SUCCESS = "API_SIGNUP_SUCCESS";
export const API_SIGNUP_ERROR = "API_SIGNUP_ERROR";

// get Affirmations
export const API_GETAFFIRMATION_LOAD = "API_GETAFFIRMATION_LOAD";
export const API_GETAFFIRMATION_START = "API_GETAFFIRMATION_START";
export const API_GETAFFIRMATION_SUCCESS = "API_GETAFFIRMATION_SUCCESS";
export const API_GETAFFIRMATION_ERROR = "API_GETAFFIRMATION_ERROR";

// get Affirmations
export const API_GETAFFIRMATION_BY_ID_LOAD = "API_GETAFFIRMATION_BY_ID_LOAD";
export const API_GETAFFIRMATION_BY_ID_START = "API_GETAFFIRMATION_BY_ID_START";
export const API_GETAFFIRMATION_BY_ID_SUCCESS =
  "API_GETAFFIRMATION_BY_ID_SUCCESS";
export const API_GETAFFIRMATION_BY_ID_ERROR = "API_GETAFFIRMATION_BY_ID_ERROR";

// ceate Affirmations
export const API_CREATE_AFFIRMATION_LOAD = "API_CREATE_AFFIRMATION_LOAD";
export const API_CREATE_AFFIRMATION_START = "API_CREATE_AFFIRMATION_START";
export const API_CREATE_AFFIRMATION_SUCCESS = "API_CREATE_AFFIRMATION_SUCCESS";
export const API_CREATE_AFFIRMATION_ERROR = "API_CREATE_AFFIRMATION_ERROR";

// my tracker get all month entry
export const API_GET_TRACKER_ALL_ENTRY_LOAD = "API_GET_TRACKER_ALL_ENTRY_LOAD";
export const API_GET_TRACKER_ALL_ENTRY_START =
  "API_GET_TRACKER_ALL_ENTRY_START";
export const API_GET_TRACKER_ALL_ENTRY_SUCCESS =
  "API_GET_TRACKER_ALL_ENTRY_SUCCESS";
export const API_GET_TRACKER_ALL_ENTRY_ERROR =
  "API_GET_TRACKER_ALL_ENTRY_ERROR";

// my tracker get entry
export const API_GET_TRACKER_ENTRY_LOAD = "API_GET_TRACKER_ENTRY_LOAD";
export const API_GET_TRACKER_ENTRY_START = "API_GET_TRACKER_ENTRY_START";
export const API_GET_TRACKER_ENTRY_SUCCESS = "API_GET_TRACKER_ENTRY_SUCCESS";
export const API_GET_TRACKER_ENTRY_ERROR = "API_GET_TRACKER_ENTRY_ERROR";

// my tracker delete entry
export const API_DELETE_TRACKER_ENTRY_LOAD = "API_DELETE_TRACKER_ENTRY_LOAD";
export const API_DELETE_TRACKER_ENTRY_START = "API_DELETE_TRACKER_ENTRY_START";
export const API_DELETE_TRACKER_ENTRY_SUCCESS =
  "API_DELETE_TRACKER_ENTRY_SUCCESS";
export const API_DELETE_TRACKER_ENTRY_ERROR = "API_DELETE_TRACKER_ENTRY_ERROR";

// my tracker edit entry
export const API_EDIT_TRACKER_ENTRY_LOAD = "API_EDIT_TRACKER_ENTRY_LOAD";
export const API_EDIT_TRACKER_ENTRY_START = "API_EDIT_TRACKER_ENTRY_START";
export const API_EDIT_TRACKER_ENTRY_SUCCESS = "API_EDIT_TRACKER_ENTRY_SUCCESS";
export const API_EDIT_TRACKER_ENTRY_ERROR = "API_EDIT_TRACKER_ENTRY_ERROR";

// my tracker create entry
export const API_CREATE_TRACKER_ENTRY_LOAD = "API_CREATE_TRACKER_ENTRY_LOAD";
export const API_CREATE_TRACKER_ENTRY_START = "API_CREATE_TRACKER_ENTRY_START";
export const API_CREATE_TRACKER_ENTRY_SUCCESS =
  "API_CREATE_TRACKER_ENTRY_SUCCESS";
export const API_CREATE_TRACKER_ENTRY_ERROR = "API_CREATE_TRACKER_ENTRY_ERROR";
