// Login
export const API_LOGIN_LOAD = "API_LOGIN_LOAD";
export const API_LOGIN_START = "API_LOGIN_START";
export const API_LOGIN_SUCCESS = "API_LOGIN_SUCCESS";
export const API_LOGIN_ERROR = "API_LOGIN_ERROR";

// omniauth
export const API_OMNIAUTH_LOAD = "API_OMNIAUTH_LOAD";
export const API_OMNIAUTH_START = "API_OMNIAUTH_START";
export const API_OMNIAUTH_SUCCESS = "API_OMNIAUTH_SUCCESS";
export const API_OMNIAUTH_ERROR = "API_OMNIAUTH_ERROR";

// Signup
export const API_SIGNUP_LOAD = "API_SIGNUP_LOAD";
export const API_SIGNUP_START = "API_SIGNUP_START";
export const API_SIGNUP_SUCCESS = "API_SIGNUP_SUCCESS";
export const API_SIGNUP_ERROR = "API_SIGNUP_ERROR";

// Mobile Token
export const API_UPDATE_MOBILE_TOKEN = "API_UPDATE_MOBILE_TOKEN";

// get Affirmations
export const API_GETAFFIRMATION_LOAD = "API_GETAFFIRMATION_LOAD";
export const API_GETAFFIRMATION_START = "API_GETAFFIRMATION_START";
export const API_GETAFFIRMATION_SUCCESS = "API_GETAFFIRMATION_SUCCESS";
export const API_GETAFFIRMATION_ERROR = "API_GETAFFIRMATION_ERROR";

// get Affirmations
export const API_GETAFFIRMATION_BY_ID_LOAD = "API_GETAFFIRMATION_BY_ID_LOAD";
export const API_GETAFFIRMATION_BY_ID_START = "API_GETAFFIRMATION_BY_ID_START";
export const API_GETAFFIRMATION_BY_ID_SUCCESS =
  "API_GETAFFIRMATION_BY_ID_SUCCESS";
export const API_GETAFFIRMATION_BY_ID_ERROR = "API_GETAFFIRMATION_BY_ID_ERROR";

// clear Affirmations data
export const API_CLEAR_REDUCER_AFFIRMATION_LOAD =
  "API_CLEAR_REDUCER_AFFIRMATION_LOAD";
export const API_CLEAR_REDUCER_AFFIRMATION_START =
  "API_CLEAR_REDUCER_AFFIRMATION_START";
export const API_CLEAR_REDUCER_AFFIRMATION_SUCCESS =
  "API_CLEAR_REDUCER_AFFIRMATION_SUCCESS";
export const API_CLEAR_REDUCER_AFFIRMATION_ERROR =
  "API_CLEAR_REDUCER_AFFIRMATION_ERROR";

// ceate Affirmations
export const API_CREATE_AFFIRMATION_LOAD = "API_CREATE_AFFIRMATION_LOAD";
export const API_CREATE_AFFIRMATION_START = "API_CREATE_AFFIRMATION_START";
export const API_CREATE_AFFIRMATION_SUCCESS = "API_CREATE_AFFIRMATION_SUCCESS";
export const API_CREATE_AFFIRMATION_ERROR = "API_CREATE_AFFIRMATION_ERROR";

// my tracker get all month entry
export const API_GET_TRACKER_ALL_ENTRY_LOAD = "API_GET_TRACKER_ALL_ENTRY_LOAD";
export const API_GET_TRACKER_ALL_ENTRY_START =
  "API_GET_TRACKER_ALL_ENTRY_START";
export const API_GET_TRACKER_ALL_ENTRY_SUCCESS =
  "API_GET_TRACKER_ALL_ENTRY_SUCCESS";
export const API_GET_TRACKER_ALL_ENTRY_ERROR =
  "API_GET_TRACKER_ALL_ENTRY_ERROR";

// my tracker get entry
export const API_GET_TRACKER_ENTRY_LOAD = "API_GET_TRACKER_ENTRY_LOAD";
export const API_GET_TRACKER_ENTRY_START = "API_GET_TRACKER_ENTRY_START";
export const API_GET_TRACKER_ENTRY_SUCCESS = "API_GET_TRACKER_ENTRY_SUCCESS";
export const API_GET_TRACKER_ENTRY_ERROR = "API_GET_TRACKER_ENTRY_ERROR";

// my tracker delete entry
export const API_DELETE_TRACKER_ENTRY_LOAD = "API_DELETE_TRACKER_ENTRY_LOAD";
export const API_DELETE_TRACKER_ENTRY_START = "API_DELETE_TRACKER_ENTRY_START";
export const API_DELETE_TRACKER_ENTRY_SUCCESS =
  "API_DELETE_TRACKER_ENTRY_SUCCESS";
export const API_DELETE_TRACKER_ENTRY_ERROR = "API_DELETE_TRACKER_ENTRY_ERROR";

// my tracker edit entry
export const API_EDIT_TRACKER_ENTRY_LOAD = "API_EDIT_TRACKER_ENTRY_LOAD";
export const API_EDIT_TRACKER_ENTRY_START = "API_EDIT_TRACKER_ENTRY_START";
export const API_EDIT_TRACKER_ENTRY_SUCCESS = "API_EDIT_TRACKER_ENTRY_SUCCESS";
export const API_EDIT_TRACKER_ENTRY_ERROR = "API_EDIT_TRACKER_ENTRY_ERROR";

// my tracker create entry
export const API_CREATE_TRACKER_ENTRY_LOAD = "API_CREATE_TRACKER_ENTRY_LOAD";
export const API_CREATE_TRACKER_ENTRY_START = "API_CREATE_TRACKER_ENTRY_START";
export const API_CREATE_TRACKER_ENTRY_SUCCESS =
  "API_CREATE_TRACKER_ENTRY_SUCCESS";
export const API_CREATE_TRACKER_ENTRY_ERROR = "API_CREATE_TRACKER_ENTRY_ERROR";

// submit feedback autodrum
export const API_SUBMIT_FEEDBACK_AUTODRUM_LOAD =
  "API_SUBMIT_FEEDBACK_AUTODRUM_LOAD";
export const API_SUBMIT_FEEDBACK_AUTODRUM_START =
  "API_SUBMIT_FEEDBACK_AUTODRUM_START";
export const API_SUBMIT_FEEDBACK_AUTODRUM_SUCCESS =
  "API_SUBMIT_FEEDBACK_AUTODRUM_SUCCESS";
export const API_SUBMIT_FEEDBACK_AUTODRUM_ERROR =
  "API_SUBMIT_FEEDBACK_AUTODRUM_ERROR";

// updtae question id
export const API_UPDATE_QUESTION_ID_LOAD = "API_UPDATE_QUESTION_ID_LOAD";
export const API_UPDATE_QUESTION_ID_START = "API_UPDATE_QUESTION_ID_START";
export const API_UPDATE_QUESTION_ID_SUCCESS = "API_UPDATE_QUESTION_ID_SUCCESS";
export const API_UPDATE_QUESTION_ID_ERROR = "API_UPDATE_QUESTION_ID_ERROR";

// updtae TOC
export const API_UPDATE_TOC_LOAD = "API_UPDATE_TOC_LOAD";
export const API_UPDATE_TOC_START = "API_UPDATE_TOC_START";
export const API_UPDATE_TOC_SUCCESS = "API_UPDATE_TOC_SUCCESS";
export const API_UPDATE_TOC_ERROR = "API_UPDATE_TOC_ERROR";

// delete Affirmations
export const API_DELETE_AFFIRMATION_LOAD = "API_DELETE_AFFIRMATION_LOAD";
export const API_DELETE_AFFIRMATION_START = "API_DELETE_AFFIRMATION_START";
export const API_DELETE_AFFIRMATION_SUCCESS = "API_DELETE_AFFIRMATION_SUCCESS";
export const API_DELETE_AFFIRMATION_ERROR = "API_DELETE_AFFIRMATION_ERROR";

// update Affirmations
export const API_UPDATE_AFFIRMATION_LOAD = "API_UPDATE_AFFIRMATION_LOAD";
export const API_UPDATE_AFFIRMATION_START = "API_UPDATE_AFFIRMATION_START";
export const API_UPDATE_AFFIRMATION_SUCCESS = "API_UPDATE_AFFIRMATION_SUCCESS";
export const API_UPDATE_AFFIRMATION_ERROR = "API_UPDATE_AFFIRMATION_ERROR";

//commit
//get Profile
export const GET_PROFILE_LOAD = "GET_PROFILE_LOAD";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";

// UPDATE PROFILE
export const UPDATE_PROFILE_LOAD = "UPDATE_PROFILE_LOAD";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

// update profile image
export const UPDATE_PROFILE_IMAGE_LOAD = "UPDATE_PROFILE_IMAGE_LOAD";
export const UPDATE_PROFILE_IMAGE_SUCESS = "UPDATE_PROFILE_IMAGE_SUCESS";
export const UPDATE_PROFILE_IMAGE_FAIL = "UPDATE_PROFILE_IMAGE_FAIL";
export const UPDATE_PROFILE_IMAGE_ERROR = "UPDATE_PROFILE_IMAGE_ERROR";

// CHANGE PASSWORD
export const CHANGE_PASSWORD_LOAD = "CHANGE_PASSWORD_LOAD";
export const CHANGE_PASSWORD_SUCESS = "CHANGE_PASSWORD_SUCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const WELLBEING_CATEGORIES_LOAD = "WELLBEING_CATEGORIES_LOAD";
export const WELLBEING_CATEGORIES_SUCESS = "WELLBEING_CATEGORIES_SUCESS";
export const WELLBEING_CATEGORIES_FAIL = "WELLBEING_CATEGORIES_FAIL";
export const WELLBEING_CATEGORIES_ERROR = "WELLBEING_CATEGORIES_ERROR";

export const WELLBEING_CATEGORIES_POSTS_LOAD =
  "WELLBEING_CATEGORIES_POSTS_LOAD";
export const WELLBEING_CATEGORIES_POSTS_SUCESS =
  "WELLBEING_CATEGORIES_POSTS_SUCESS";
export const WELLBEING_CATEGORIES_POSTS_FAIL =
  "WELLBEING_CATEGORIES_POSTS_FAIL";
export const WELLBEING_CATEGORIES_POSTS_ERROR =
  "WELLBEING_CATEGORIES_POSTS_ERROR";

export const LIKE_POST_LOAD = "LIKE_POST_LOAD";
export const LIKE_POST_SUCESS = "LIKE_POST_SUCESS";
export const LIKE_POST_FAIL = "LIKE_POST_FAIL";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";

export const GET_COMMENTS_LOAD = "GET_COMMENTS_LOAD";
export const GET_COMMENTS_SUCESS = "GET_COMMENTS_SUCESS";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";
export const GET_COMMENTS_ERROR = "GET_COMMENTS_ERROR";

export const SET_COMMENT_LOAD = "SET_COMMENT_LOAD";
export const SET_COMMENT_SUCESS = "SET_COMMENT_SUCESS";
export const SET_COMMENT_FAIL = "SET_COMMENT_FAIL";
export const SET_COMMENT_ERROR = "SET_COMMENT_ERROR";

export const SET_FLAG_USER_LOAD = "SET_FLAG_USER_LOAD";
export const SET_FLAG_USER_SUCESS = "SET_FLAG_USER_SUCESS";
export const SET_FLAG_USER_FAIL = "SET_FLAG_USER_FAIL";
export const SET_FLAG_USER_ERROR = "SET_FLAG_USER_ERROR";

export const SET_LOGIN_REDUCER_NAVIGATION = "SET_LOGIN_REDUCER_NAVIGATION";
export const SET_QUESTION_ID_REDUCER_NAVIGATION =
  "SET_QUESTION_ID_REDUCER_NAVIGATION";

  export const SET_SONGS_IN_REDUCER = 'SET_SONGS_IN_REDUCER';